# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZR5kGtbbr6ppRyNhPfzbaRhpbgAcd41h
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
import pandas as pd
import numpy as np

# Step 1: Upload the file
uploaded = files.upload()

# Step 2: Read the Excel file
file_name = list(uploaded.keys())[0]  # Get the uploaded file name
xls = pd.ExcelFile(file_name)

# List all sheet names
sheet_names = xls.sheet_names
print("Available sheets:", sheet_names)

# Load a specific sheet into a DataFrame
df = pd.read_excel(xls, sheet_name='Purchase data') # Use the correct sheet name

# Display the first few rows of the DataFrame
print(df.head())

# Step 3: Segregate data into matrices A and C
A = df.iloc[:, 1:4].values  # Extract features (assume columns 1 to 3 are features)
C = df.iloc[:, 4].values    # Extract target (assume column 4 is the target)

print("Matrix A:\n", A)
print("Vector C:\n", C)